djangoproject/djangoproject/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('match.urls', namespace="match")),
    url(r'^admin/', include(admin.site.urls)),
)

djangoproject/match/urls.py
from django.conf.urls import patterns, url

from match import views

urlpatterns = patterns('',
	url(r'^$', views.home, name='home'),
	url(r'^profiles/$', views.profiles, name='profiles'),
	url(r'^profiles/(?P<profile_id>\d+)$', views.profile, name='profile'),
	url(r'^groups/$', views.groups, name='groups'),
	url(r'^groups/(?P<tag_id>\d+)$', views.group, name='group'),
	url(r'^signup/$', views.signup, name='signup'),
)

djangoproject/match/models.py
from django.db import models
from django import forms
import datetime

from django.db.models.signals import * #selective import
from django.db.transaction import commit_on_success

# ------------ Utils ---------------------
# Import better

def tanimoto(u1, u2):
	"""
	u1, u2 are profile instances from a queryset
	returns number between 0.0 and 1.0
	"""
	t1 = u1.tags.all()
	t2 = u2.tags.all()

	c1 = len(t1)
	c2 = len(t2)
	shr = len(set(t1).intersection(t2))

	try:
		return float(shr)/(c1 + c2 - shr)
	except ZeroDivisionError:
		return 0.0

# http://stackoverflow.com/questions/3395236/aggregating-saves-in-django
@commit_on_success
def load_distances(from_profile):
	profiles = Profile.objects.all()
	distances = []

	for to_profile in profiles:
		d = tanimoto(from_profile, to_profile)

		# from profile
		#TODO check if the distance exists first to avoid duplicate
		distance = Distance.objects.create(from_profile=from_profile, to_profile=to_profile, d=d)
		distances.append(distance)

		# to profile
		distance = Distance.objects.create(from_profile=to_profile, to_profile=from_profile, d=d)
		to_profile.distances.add(distance)

	from_profile.distances.add(*distances)


# ------------ Models --------------------

class Tag(models.Model):
	name = models.CharField(max_length=30)

	def __unicode__(self):
		return self.name

class Distance(models.Model):
	from_profile = models.ForeignKey('Profile', related_name = 'from_profile') # 'Profile' lets Django know that the reference may still be under construction.
	to_profile = models.ForeignKey('Profile', related_name = 'to_profile') #
	d = models.FloatField()

	def __unicode__(self):
		return "{0:.2f} to {1}".format(self.d, self.to_profile)

class Profile(models.Model):
	name = models.CharField(max_length=20) #unique=True
	email = models.EmailField()
	date = models.DateTimeField(auto_now=True)
	tags = models.ManyToManyField('Tag', blank=True, null=True, related_name = 'profiles')
	distances = models.ManyToManyField('Distance', blank=True, null=True)

	def closer(self):
		#return self.distances.filter(d__lte=0.5).exclude(to_user=self).order_by('d')[:5]
		return self.distances.exclude(to_profile=self).filter(d__gt=0).order_by('d').reverse()[:5]

	def __unicode__(self):
		return self.name


# ------------- Forms --------------------------

#http://stackoverflow.com/questions/949268/django-accessing-the-model-instance-from-within-modeladmin
class ProfileForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(ProfileForm, self).__init__(*args, **kwargs)
		self.fields['tags'].queryset = self.instance.tags.all()
		self.fields['distances'].queryset = self.instance.distances.all().filter(d__gt=0).order_by('d')


# ------------- Signals ------------------------

def tags_changed(sender, **kwargs):
	if kwargs["action"] == "post_add":
		profile = kwargs["instance"]
		load_distances(profile)

m2m_changed.connect(tags_changed, sender=Profile.tags.through, weak=False)

#When changing models:
#python manage.py sqlclear match | python manage.py dbshell
#python manage.py syncdb

# CHECK south for django 1.6
# CHECK django migrations for django 1.7

djangoproject/match/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from match.models import Profile, Distance, Tag

def home(request):

	return render(request, 'match/home.html', {})

def profiles(request):

	profiles = Profile.objects.all()

	return render(request, 'match/profiles.html', {
		'profiles': profiles,
	})

def profile(request, profile_id):
	profile = get_object_or_404(Profile, pk=profile_id)
	return render(request, 'match/profile.html', {
		'profile': profile,
	})

def groups(request):
	tags = Tag.objects.all()

	return render(request, 'match/interests.html', {
		'tags': tags,
	})

def group(request, tag_id):
	tag = get_object_or_404(Tag, pk=tag_id)

	return render(request, 'match/interest.html', {
		'tag': tag,
	})

def signup(request):

	if request.method == "POST":

		name = request.POST["name"] or "Anonymous"
		email = request.POST["email"]
		selected_tags_ids = request.POST.getlist("tag")
		#selected tags ids will be a list of ids taken from the value input attribute
		#For a checkbox it contains those checked
		#tag = Tag.objects.get(id=selected_tags[0])

		if not selected_tags_ids:
			errors = "select some interests"
			tags = Tag.objects.all()
			return render(request, 'match/register.html', {
				'tags': tags,
				'name': name,
				'email': email,
				'errors': errors,
			})

		profile = Profile.objects.create(name=name, email=email)
		tags = Tag.objects.filter(id__in=selected_tags_ids)
		profile.tags.add(*tags) # in models tags_changed() signal to add distances

		return HttpResponseRedirect('/profiles/' + '%s' % profile.id )

	else:

		tags = Tag.objects.all()

		return render(request, 'match/register.html', {
			'tags': tags,
		})

djangoproject/match/templates/match/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<title>IT Match: connect IT students in Metropolia</title>
	<meta name="viewport" content="width=device-width, user-scalable=no">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
	<div class="container">
    	<div class="header">
			<ul class="nav nav-pills pull-right">
				{% block navbar %}
				{% endblock %}
			</ul>
			<h3 class="text-muted"><img src="{% static 'logo.png' %}" /> IT Match</h3>
		</div>
		<div class="jumbotron">
			{% block content %}
			{% endblock %}
		</div> <!-- jumbotron -->
	    <div class="footer">
	    	<p>@Metropolia 2014
			<iframe class="pull-right" src="http://ghbtns.com/github-btn.html?user=arimbr&repo=itmatch&type=fork&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="80" height="20"></iframe></p>
    	</div>
	</div> <!-- container -->

	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-50633286-1', 'itmatch.herokuapp.com');
		ga('send', 'pageview');
	</script>
</body>
</html>

djangoproject/match/templates/match/home.html
{% extends "match/base.html" %}
{% block navbar %}
	<li class="active"><a href={% url 'match:home' %}>Home</a></li>
	<li><a href={% url 'match:profiles' %}>Profiles</a></li>
	<li><a href={% url 'match:groups' %}>Groups</a></li>
	<li><a href={% url 'match:signup' %}>Signup</a></li>
{% endblock %}
{% block content %}
	<h1>IT Match</h1>
	<p class="lead">Connect with other students with similar IT interests in Leppävaara Campus. Build something together and foster your career.</p>
	<p><a class="btn btn-lg btn-success" href={% url 'match:signup' %} role="button">Sign up</a></p>
{% endblock %}

djangoproject/match/templates/match/interest.html
{% extends "match/base.html" %}

{% block navbar %}
	<li><a href={% url 'match:home' %}>Home</a></li>
	<li><a href={% url 'match:profiles' %}>Profiles</a></li>
	<li><a href={% url 'match:groups' %}>Groups</a></li>
	<li><a href={% url 'match:signup' %}>Signup</a></li>
{% endblock %}
{% block content %}
	<div class="well well-sm">
		<h2 class="custom-block">{{ tag.name }}</h2>
	</div>
	<h3>Members</h3>
	{% for profile in tag.profiles.all %}
		<a href="{% url 'match:profile' profile.id %}">{{ profile.name }}</a>{% if not forloop.last %}, {% endif %}
	{% endfor %}
{% endblock %}

djangoproject/match/templates/match/interests.html
{% extends "match/base.html" %}

{% block navbar %}
	<li><a href={% url 'match:home' %}>Home</a></li>
	<li><a href={% url 'match:profiles' %}>Profiles</a></li>
	<li class="active"><a href={% url 'match:groups' %}>Groups</a></li>
	<li><a href={% url 'match:signup' %}>Signup</a></li>
{% endblock %}
{% block content %}
	<div class="well well-sm">
		<h2 class="custom-block">{{ tags.all.count }} Groups</h2>
	</div>
	{% for tag in tags|dictsortreversed:"profiles.count" %}
		<p>
			<h3><a href='{{tag.id}}'>{{ tag.name }}</a> ({{ tag.profiles.count }})</h3>
		</p>
	{% endfor %}
{% endblock %}

djangoproject/match/templates/match/profile.html
{% extends "match/base.html" %}

{% block navbar %}
	<li><a href={% url 'match:home' %}>Home</a></li>
	<li><a href={% url 'match:profiles' %}>Profiles</a></li>
	<li><a href={% url 'match:groups' %}>Groups</a></li>
	<li><a href={% url 'match:signup' %}>Signup</a></li>
{% endblock %}
{% block content %}
	<div class="well well-sm">
		<h2 class="custom-block">{{ profile.name }}</h2>
	</div>
	<div>
		<h3>Interests</h3>
		{% for tag in profile.tags.all %}
			<a href={% url 'match:group' tag.id %}>{{ tag.name }}</a>{% if not forloop.last %},{% endif %}
		{% endfor %}
	</div>
	<div>
		<h3>Similar profiles</h3>
		{% for distance in profile.closer %}
			<a href="{{ distance.to_profile.id }}">{{ distance.to_profile.name }}</a> ({{ distance.d | floatformat:1 }}){% if not forloop.last %}, {% endif %}
		{% endfor %}
	</div>
{% endblock %}

djangoproject/match/templates/match/profiles.html
{% extends "match/base.html" %}

{% block navbar %}
	<li><a href={% url 'match:home' %}>Home</a></li>
	<li class="active"><a href={% url 'match:profiles' %}>Profiles</a></li>
	<li><a href={% url 'match:groups' %}>Groups</a></li>
	<li><a href={% url 'match:signup' %}>Signup</a></li>
{% endblock %}
{% block content %}
	<div class="well well-sm">
		<h2 class="custom-block">{{ profiles.all.count }} Profiles</h2>
	</div>
	{% for profile in profiles|dictsortreversed:"id" %}
		<p>
			<h3><a href="/profiles/{{ profile.id }}">{{ profile.name }}</a></h3>
			{% for tag in profile.tags.all %}
				<span class="normal">{{ tag.name }}</span>{% if not forloop.last %},{% endif %}
			{% endfor %}
		</p>
	{% endfor %}
{% endblock %}

djangoproject/match/templates/match/register.html
{% extends "match/base.html" %}

{% block navbar %}
	<li><a href={% url 'match:home' %}>Home</a></li>
	<li><a href={% url 'match:profiles' %}>Profiles</a></li>
	<li><a href={% url 'match:groups' %}>Groups</a></li>
	<li class="active"><a href={% url 'match:signup' %}>Signup</a></li>
{% endblock %}
{% block content %}
	<div class="well well-sm">
		<h2 class="custom-block">Foster your career</h2>
	</div>
	<form class="row left" action="{% url 'match:signup' %}" method="post">
		{% csrf_token %}
		<label for="name">Full name:</label>
		<br />
		<input type="text" class="form-control" name="name" id="name" placeholder="" value="{{ name }}" autofocus />
		<br />
		<label for="email">Metropolia email:</label>
		<br />
		<input type="text" class="form-control" name="email" id="email" placeholder="" value="{{ email }}"/>
		<!--<label class="checkbox">
      		<input type="checkbox" value="remember-me" checked><span class="normal">Notify me at launch</span>
    	</label> -->

    	<br />
    	<label>Interests: <span class="error">{{ errors }}</span></label>
		<br />
		{% for tag in tags.all|dictsortreversed:"profiles.count" %}
		    <input type="checkbox" name="tag" id="tag{{ forloop.counter }}" value="{{ tag.id }}" />
		    <label class="normal" for="tag{{ forloop.counter }}">{{ tag.name }}</label><br />
		{% endfor %}
		<br />

		<button class="btn btn-lg btn-primary btn-block" type="submit" onclick="this.disabled=true,this.form.submit();">Sign up</button>
		<br />
	</form>
{% endblock %}